# Generated by Django 3.2.13 on 2022-11-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221117_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='department',
            new_name='job',
        ),
    ]
