# Generated by Django 3.2.13 on 2022-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_department_credit_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('known_for_department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.IntegerField()),
                ('profile_path', models.CharField(blank=True, max_length=200, null=True)),
                ('character', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('known_for_department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.IntegerField()),
                ('profile_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
