# Generated by Django 3.2.13 on 2022-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20221117_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actorlist',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('known_for_department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('character', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directorlist',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('known_for_department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonMovie',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='character',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='known_for_department',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='director',
            name='known_for_department',
        ),
        migrations.RemoveField(
            model_name='director',
            name='popularity',
        ),
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
