# Generated by Django 3.2.13 on 2022-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20221117_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actormovie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directormovie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
    ]
